var lvls = [{
    sea: SEA_MORN,
    background1: BACKGROUND_MORN,
    background2: BACKGROUND_MORN2,
    day: MORN_OBJECTS,
    wave: WAVE_CRUSH_MORN,
    shouldLoadWave: false,
    time: 5,
}, {
    sea: SEA_NOON,
    background1: BACKGROUND_NOON,
    background2: BACKGROUND_NOON2,
    day: NOON_OBJECTS,
    wave: WAVE_CRUSH_NOON,
    shouldLoadWave: true,
    time: 5,
}, {
    sea: SEA_NIGHT,
    background1: BACKGROUND_NIGHT,
    background2: BACKGROUND_NIGHT2,
    day: NIGHT_OBJECTS,
    wave: WAVE_CRUSH_NIGHT,
    shouldLoadWave: true,
    time: 5,
}]